[package]
name = "castflip_derive"
version = "0.1.10"
edition = "2024"
description = "Derive macros for the castflip crate"
license = "MIT-0"
readme = "README.md"
repository = "https://github.com/noriov/castflip"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
